/* THE DOOR INDEX: every question the engine answers, and what answers it.
 *
 *   node doors.js            write DOORS.md
 *   node doors.js --check    fail if DOORS.md is not what the engine says
 *
 * Why this exists, in one sentence: twice in two days something was built that
 * already existed. L.PALATE was written as a flavour vocabulary on 2026-09-26
 * when L.FLAVORS had been one since the 17th; a palate PROFILE was prototyped
 * on the 27th when L.tasteProfile had been calling its own since long before.
 * Both were missed the same way - the existing door is named in a different
 * vocabulary (FLAVORS against PALATE, tasteProfile against "palate profile"),
 * and consistency.js compares function SHAPES, so a rule written differently is
 * invisible to it. With 758 L functions, grep on a guessed name is not a
 * reliable way to find the door.
 *
 * So: a generated list, sorted by name, each with the first line of whatever
 * the author wrote above it. Generated rather than maintained, because a hand-
 * written index of 758 things is a lie within a week - and checked by
 * consistency.js, so it cannot quietly fall behind the engine it describes.
 */
const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, 'index.html');
const OUT = path.join(__dirname, 'DOORS.md');

/* The comment block immediately above a definition, as one line. This
   project's convention is that the block opens with WHY, often in capitals,
   so the first sentence is the useful part. */
function purposeAbove(lines, i) {
  let j = i - 1;
  const block = [];
  /* A BLOCK IN THIS FILE'S STYLE, whose continuation lines are plain indented
     text rather than starred. Walking back and stopping at the first line that
     did not look like a comment therefore collected the LAST line of a block
     and nothing else, which is how a tail - "drinker is offered a rye" - was
     read as the purpose. So: once the closing `*/` is seen, keep walking until
     the opening `/*`. A blank line still breaks the association, because a
     comment two lines up belongs to whatever sits between them. */
  /* A CONSTANT BETWEEN THE COMMENT AND THE FUNCTION still leaves the comment
     describing both: L.shelfLeans sits under a headline separated from it by
     the one line that declares its band. So a single-line declaration is
     stepped over rather than treated as the end of the story. */
  while (j >= 0 && /^L\.[A-Za-z_0-9]+ = .*;\s*$/.test(lines[j].trim())) j--;
  let inside = false;
  while (j >= 0) {
    const t = lines[j].trim();
    if (!t) break;
    if (!inside && t.startsWith('//')) { block.unshift(t); break; }
    if (!inside && !t.endsWith('*/')) break;
    inside = true;
    block.unshift(t);
    if (t.startsWith('/*')) break;
    j--;
  }
  if (!block.length) return '';
  /* THE OPENING LINE, not the first sentence of the joined block. This
     project's convention is that a comment opens with the why, often in
     capitals, and joining the block first meant a tail like "drinker is
     offered a rye" was picked up as the purpose. Where the opening line is
     bare - just `/*` - the next one carries it. */
  const clean = t => t
    .replace(/^\/\*+/, '').replace(/\*+\/$/, '')
    .replace(/^\s*\*+/, '').replace(/^\s*\/\//, '')
    .replace(/\s+/g, ' ').trim();
  let first = '';
  for (let k = 0; k < block.length && !first; k++) first = clean(block[k]);
  if (!first) return '';
  /* A headline that runs on gets its first clause, so the list stays one
     line per door. */
  const stop = first.search(/[.;:]\s/);
  if (stop > 0 && stop >= 12) first = first.slice(0, stop);
  return first.length > 120 ? first.slice(0, 117) + '…' : first;
}

function read() {
  const lines = fs.readFileSync(SRC, 'utf8').split('\n');
  const out = [];
  lines.forEach((l, i) => {
    const fn = /^L\.([a-zA-Z_0-9]+) = function/.exec(l);
    const tbl = /^L\.([A-Z][A-Z_0-9]*) = [[{]/.exec(l);
    const m = fn || tbl;
    if (!m) return;
    out.push({ name: m[1], kind: fn ? 'fn' : 'table',
               why: purposeAbove(lines, i) });
  });
  out.sort((a, b) => a.name.toLowerCase() < b.name.toLowerCase() ? -1 : 1);
  return out;
}

function render(doors) {
  const fns = doors.filter(d => d.kind === 'fn');
  const tbl = doors.filter(d => d.kind === 'table');
  const lines = [];
  lines.push('# The doors');
  lines.push('');
  lines.push('**Generated by `node doors.js`. Do not edit.** `consistency.js`');
  lines.push('fails if this file and the engine disagree.');
  lines.push('');
  lines.push('Before writing a function, look for the one that already answers');
  lines.push('the question. Twice in two days something was built that existed:');
  lines.push('a flavour vocabulary beside `L.FLAVORS`, and a palate profile');
  lines.push('beside `L.tasteProfile`. Both were named in a different');
  lines.push('vocabulary from the thing they duplicated, which is why grep on a');
  lines.push('guessed name did not find them. Search this file for the');
  lines.push('QUESTION, not the name you were going to use.');
  lines.push('');
  lines.push('| | |');
  lines.push('|---|---|');
  lines.push('| functions | ' + fns.length + ' |');
  lines.push('| tables | ' + tbl.length + ' |');
  lines.push('| carrying a stated purpose | '
    + doors.filter(d => d.why).length + ' |');
  lines.push('');
  lines.push('## Tables');
  lines.push('');
  tbl.forEach(d => lines.push('- **`L.' + d.name + '`** — '
    + (d.why || '_no comment above it_')));
  lines.push('');
  lines.push('## Functions');
  lines.push('');
  fns.forEach(d => lines.push('- **`L.' + d.name + '`** — '
    + (d.why || '_no comment above it_')));
  lines.push('');
  return lines.join('\n');
}

const doors = read();
const text = render(doors);

if (process.argv.indexOf('--check') >= 0) {
  let had = '';
  try { had = fs.readFileSync(OUT, 'utf8'); } catch (e) { had = ''; }
  if (had === text) {
    console.log('  ✓ the door index matches the engine ('
      + doors.length + ' doors)');
    process.exit(0);
  }
  console.log('  ✖ DOORS.md is not what the engine says — '
    + 'run `node doors.js`');
  process.exit(1);
}

fs.writeFileSync(OUT, text);
console.log('  DOORS.md written: ' + doors.length + ' doors, '
  + doors.filter(d => d.why).length + ' with a stated purpose');
